### ISSUE TITLE
OnlyOffice SSL (feature/ssl)

### ISSUE THREAD

**Issue by LinuxOperator** [ONLYOFFICE/docker-onlyoffice-nextcloud#45]
I was testing the branch "feature/ssl" this week with a lot of excitement because I know SSL has been an issue with this project for a long time.

I know this is probably a work in progress but I am impressed with the progress in this branch. **Please let me know if anyone knows what the problem is and I will happily test it and possibly commit the fixes.**

Problem:
- Onlyoffice is not able to communicate with nextcloud over HTTPS
![image](https://user-images.githubusercontent.com/68796633/96527009-150eb800-124d-11eb-9f59-92fcf1df0aa4.png)

Steps:
- Install
- Copy SSL cert to folder "certs"
- docker-compose -f docker-compose.yml -f ssl.yml up -d
- bash set_configuration.sh ssl

Environment:

- CentOS 8
-Firewall rules:
```
sudo firewall-cmd --permanent --zone=public --add-service=http 
sudo firewall-cmd --permanent --zone=public --add-service=https
sudo firewall-cmd --zone=public --add-masquerade --permanent
sudo firewall-cmd --reload

```

**Comment by LinneyS** [comment]
@heatray

**Comment by heatray** [comment]
Not finished work on it yet.
At the moment, to work, you need to uncomment lines in ssl.yml
```yml
  onlyoffice-document-server:
    environment:
      - USE_UNAUTHORIZED_STORAGE=true
```

**Comment by LinuxOperator** [comment]
Thank you!! That worked great, thanks for making this branch it saved me a ton of work!

For anyone else trying this .yml files are really picky with indentations. Make sure that each indentation is exactly 2 spaces. 
Here is the working ssl.yml file:
 ``````````
version: '3'
services:
  ## Uncomment these lines for using self-signed SSL certificate
  onlyoffice-document-server:
    environment:
      - USE_UNAUTHORIZED_STORAGE=true
  nginx:
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx-ssl.conf:/etc/nginx/nginx.conf
``````````
